name: Scheduled Cloudflare Pages Rebuild

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment:
      name: cloudflare-api
    steps:
      - name: Trigger Cloudflare Pages deployment
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PROJECT_NAME }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: multipart/form-data"
