name: Scheduled Cloudflare Pages Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'    # JST 09:00
    - cron: '0 2 * * *'    # JST 11:00
    - cron: '0 4 * * *'    # JST 13:00
    - cron: '0 6 * * *'    # JST 15:00
    - cron: '0 8 * * *'    # JST 17:00
    - cron: '0 10 * * *'   # JST 19:00
    - cron: '0 12 * * *'   # JST 21:00
    - cron: '0 14 * * *'   # JST 23:00

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment:
      name: cloudflare-api
    steps:
      - name: Trigger Cloudflare Pages deployment
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ secrets.CLOUDFLARE_PROJECT_NAME }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: multipart/form-data"
